### PR TITLE
fix(slack): Use global provider object

### LINKED ISSUE #3769: [Bug]: Slack integration failing with version 4
### Steps to Reproduce

I am using the --slack switch along with the 2 x SLACK environment variables to send a message to our slack channel. This is working fine in Prowler 3.14.0, however with the latest version 4.0.1 we do not recieve any messages in slack

### Expected behavior

Recieve slack messages in existing slack channel

### Actual Result with Screenshots or Logs

{"timestamp": "2024-04-15 12:25:02,549", "filename": "slack.py:55", "level": "ERROR", "module": "slack", "message": "AttributeError[41]: 'str' object has no attribute 'type'"}
{"timestamp": "2024-04-15 12:25:02,549", "filename": "slack.py:21", "level": "ERROR", "module": "slack", "message": "TypeError[12]: cannot unpack non-iterable NoneType object"}

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. Fargate Task
2. WSL 2 Terminal

### OS used

1. Alpine
2. Ubuntu

### Prowler version

4.0.1

### Pip version

3.11

### Context

_No response_

### PR DESCRIPTION
**Pull request by jfagoagas**
### Context

Fixes #3769

### Description

The Slack integration should use the `global_provider` instead of the `provider` which is just a string.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by garym-krrv** [comment]
I tested the change and this fixes the issue with the slack intergration

**Review by pedrooot — APPROVED** [review]
LGTM!
