### PR TITLE
fix(mutelist): Split code for AWS and the rest of providers

### LINKED ISSUE #4141: [Bug]: 'NoneType' object has no attribute 'client' with Prowler 4.2.1
### Steps to Reproduce

Executing prowler with a mutelist results on the error:
`[File: mutelist.py:109]         [Module: mutelist]       CRITICAL: AttributeError -- 'NoneType' object has no attribute 'client'[51]`

### Expected behavior

Works as earlier version

### Actual Result with Screenshots or Logs

[File: mutelist.py:109]         [Module: mutelist]       CRITICAL: AttributeError -- 'NoneType' object has no attribute 'client'[51]

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

3

### OS used

5. Docker official image

### Prowler version

4.2.1

### Pip version

One on docker image

### Context

It works correctly on version 4.1.0

### PR DESCRIPTION
**Pull request by jfagoagas**
### Context

Fixes #4141 

### Description

Override `mutelist` setter if AWS since we can recover the allowlist from S3, Lambda or DynamoDB.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: tests/providers/aws/lib/mutelist/aws_mutelist_test.py [hunk 1]
```diff
@@ -0,0 +1,283 @@
...
+    create_zip_file,
+)
+from tests.providers.aws.utils import (
+    AWS_ACCOUNT_NUMBER,
+    AWS_REGION_EU_WEST_1,
+    AWS_REGION_US_EAST_1,
+    set_mocked_aws_provider,
+)
+
+# Mocking Security Hub Get Findings
```
Comment (jfagoagas) [inline tests/providers/aws/lib/mutelist/aws_mutelist_test.py]:
```suggestion
```

**Review by MrCloudSec — APPROVED** [review]
I love this, thanks @jfagoagas !!
