### ISSUE TITLE
Prowler CSV Output no longer outputs Failed Critical Findings

### ISSUE THREAD

**Issue by garym-krrv** [toniblyx/prowler#5854]
### Steps to Reproduce

Running prowler 4.5.3
Execute prowler aws against an AWS account. 
CSV Outputs PASS critical findings but does output FAIL findings.

Prowler Dashboard does not display any cirtical findings

It was working with 4.3.5 but after I upgraded to 4.5.3 this now fails.

json-ocsf files are fine. These do contain Critical Fail

### Expected behavior

Failed critical findings to be contained in CSV file to use with prowler dashboard

### Actual Result with Screenshots or Logs

prowler aws --output-bucket-no-assume prowler-output-bucket-XXXXXXXXXXXX --output-directory output --slack --role arn:aws:iam::XXXXXXXXXXXX:role/XXXXXXXXXXX --role-session-name XXXXX_XXXXXX

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

2. Fargate Task running python:alpine with python 3.12

### OS used

3. Alpine Linux

### Prowler version

4.5.3

### Pip version

3.12

**Comment by pedrooot** [comment]
Hello! @garym-krrv Could you add the `--log-level ERROR` flag to your Prowler execution to see if we can find logs that indicate what the error might be?

**Comment by garym-krrv** [comment]
Will do.. let me get back to you @pedrooot 

Many Thanks

**Comment by garym-krrv** [comment]
Hey @pedrooot 

Apart from me missing the updated IAM Policy which is throwing access denied, heres 2 errors before the output

2024-11-21 15:16:01,213 [File: html.py:57] [Module: html] ERROR: AttributeError[42]: 'str' object has no attribute 'value'
2024-11-21 15:16:00,559 [File: csv.py:84] [Module: csv] ERROR: AttributeError[45]: 'str' object has no attribute 'value'

**Comment by pedrooot** [comment]
That’s the confirmation I needed 😄 . You can find the solution to your issue in this PR -> https://github.com/prowler-cloud/prowler/pull/5856

**Comment by garym-krrv** [comment]
Many Thanks.. Soon as I fix my WSL2 ill test from that branch..

**Comment by garym-krrv** [comment]
I tested against the branch and confirmed the Critical Failed findings now appear in the CSV

Many Thanks @pedrooot
