### ISSUE TITLE
[Bug]: 'NoneType' object has no attribute 'client' with Prowler 4.2.1

### ISSUE THREAD

**Issue by christiandavilakoobin** [toniblyx/prowler#4141]
### Steps to Reproduce

Executing prowler with a mutelist results on the error:
`[File: mutelist.py:109]         [Module: mutelist]       CRITICAL: AttributeError -- 'NoneType' object has no attribute 'client'[51]`

### Expected behavior

Works as earlier version

### Actual Result with Screenshots or Logs

[File: mutelist.py:109]         [Module: mutelist]       CRITICAL: AttributeError -- 'NoneType' object has no attribute 'client'[51]

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

3

### OS used

5. Docker official image

### Prowler version

4.2.1

### Pip version

One on docker image

### Context

It works correctly on version 4.1.0

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin I've created the above PR in the branch `PRWLR-3837-bug-none-type-object-has-no-attribute-client-with-prowler-4-2-1-4141`. Please test it and tell me if this works as expected.

Thanks for using Prowler 🚀

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas,

Yes, it's working now.

Thanks!

**Comment by jfagoagas** [comment]
> Hi @jfagoagas,
> 
> Yes, it's working now.
> 
> Thanks!

That's great! I'll fix some failing tests tomorrow and include some others to prevent this to happen again. Probably we will release a 4.2.2 tomorrow or Monday.

Thanks again 🙌

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin could you please test it again with the same branch? I've refactor some parts of the code make it more simpler to work with and also to separate concerns about AWS and other providers.

More tests has been included.

**Comment by christiandavilakoobin** [comment]
Hi @jfagoagas 

It fails 😢 :

```
Traceback (most recent call last):
  File "/home/prowler/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
             ^^^^^^^^^
  File "/home/prowler/.local/lib/python3.12/site-packages/prowler/__main__.py", line 204, in prowler
    global_provider.mutelist = args.mutelist_file
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prowler/.local/lib/python3.12/site-packages/prowler/providers/aws/aws_provider.py", line 322, in mutelist
    mutelist = get_mutelist_file_from_lambda(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_mutelist_file_from_lambda() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by jfagoagas** [comment]
You were faster than me! I'm just including tests for that part to prevent this from happening again.

**Comment by jfagoagas** [comment]
@christiandavilakoobin pushed changes and tests, thanks!

**Comment by christiandavilakoobin** [comment]
@jfagoagas same error. It seems you fixed the s3, but lambda still have 3 parameters instead 2.

**Comment by jfagoagas** [comment]
It should be fixed with the last commit maybe you didn't pull, could you check it?

**Comment by christiandavilakoobin** [comment]
You're right. It works now! Thanks!
