### ISSUE TITLE
[Bug]: Slack integration failing with version 4

### ISSUE THREAD

**Issue by garym-krrv** [toniblyx/prowler#3769]
### Steps to Reproduce

I am using the --slack switch along with the 2 x SLACK environment variables to send a message to our slack channel. This is working fine in Prowler 3.14.0, however with the latest version 4.0.1 we do not recieve any messages in slack

### Expected behavior

Recieve slack messages in existing slack channel

### Actual Result with Screenshots or Logs

{"timestamp": "2024-04-15 12:25:02,549", "filename": "slack.py:55", "level": "ERROR", "module": "slack", "message": "AttributeError[41]: 'str' object has no attribute 'type'"}
{"timestamp": "2024-04-15 12:25:02,549", "filename": "slack.py:21", "level": "ERROR", "module": "slack", "message": "TypeError[12]: cannot unpack non-iterable NoneType object"}

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. Fargate Task
2. WSL 2 Terminal

### OS used

1. Alpine
2. Ubuntu

### Prowler version

4.0.1

### Pip version

3.11

**Comment by garym-krrv** [comment]
I am Reviewing to see if I can fix it

**Comment by jfagoagas** [comment]
Hi @garym-krrv, could you try it with this branch `3769-bug-slack-integration-failing-with-version-4`? I know you were trying to fix it but I realised once I saw the issue.

Thanks for using Prowler 🚀

**Comment by garym-krrv** [comment]
Hey @jfagoagas thanks for looking.. Certainly.. Im on it now...

**Comment by garym-krrv** [comment]
Hi @jfagoagas , I can confirm that the slack intergration works on the branch `3769-bug-slack-integration-failing-with-version-4`
The messages are recieved in the slack channel.

Thanks for the fix
